name: common
description: Common module project.

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  logging: ^1.0.2
  intl: ^0.17.0
  dartz: ^0.10.0-nullsafety.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

publish_to: none

flutter:

  fonts:
    - family: Roboto
      fonts:
        - asset: packages/common/font/roboto_regular.ttf
        - asset: packages/common/font/roboto_bold.ttf
          weight: 700

  module:
    androidX: true
    androidPackage: com.devper.module.common
    iosBundleIdentifier: com.devper.module.common
